name: achivi
description: achivi app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  device_info: ^0.4.0+4
  http: ^0.12.0+4
  provider: ^4.0.4
  google_fonts: ^0.3.9
  flutter:
    sdk: flutter
  flutter_spinkit: "^4.1.2"
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  validators: ^2.0.0 # change to latest version
  intl: ^0.15.7
  datetime_picker_formfield: ^0.1.1
  flutter_layout_grid: ">=0.9.3"
  flutter_launcher_icons: ^0.7.3
  hexcolor: ^1.0.1
  shared_preferences: ^0.5.7

dev_dependencies:
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter
  test: ^1.5.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/defaults/defaul_avatar.png
    - assets/images/logo_achivi.png
    - assets/images/logo_achivi_white.png
    - assets/images/medaille.png
    - assets/images/cover.PNG
    - assets/images/cover_green.PNG
  #  - assets/dev_options/dev_login.json
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: FrancoisOne
     fonts:
       - asset: assets/fonts/FrancoisOne-Regular.ttf

   - family: Quicksand
     fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600

   - family: Cardo
     fonts:
       - asset: assets/fonts/Cardo-Regular.ttf
       - asset: assets/fonts/Cardo-Bold.ttf
       - asset: assets/fonts/Cardo-Italic.ttf

   - family: Oswald
     fonts:
       - asset: assets/fonts/Oswald-Regular.ttf
       - asset: assets/fonts/Oswald-Bold.ttf
       - asset: assets/fonts/Oswald-Medium.ttf
       - asset: assets/fonts/Oswald-ExtraLight.ttf
       - asset: assets/fonts/Oswald-Light.ttf
       - asset: assets/fonts/Oswald-SemiBold.ttf


   - family: PatrickHand
     fonts:
       - asset: assets/fonts/PatrickHand-Regular.ttf

   - family: PermanentMarker
     fonts:
       - asset: assets/fonts/PermanentMarker-Regular.ttf
   - family: Satisfy
     fonts:
       - asset: assets/fonts/Satisfy-Regular.ttf

   - family: SpecialElite
     fonts:
       - asset: assets/fonts/SpecialElite-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# https://stackoverflow.com/questions/43928702/how-to-change-the-application-launcher-icon-on-flutter
flutter_icons:
    image_path: "assets/images/logo_achivi.png"
    android: true
    ios: true